### ISSUE TITLE
Quickview-1.1.5 does not show StatusBar on 'Fullscreen on startup'

### ISSUE THREAD

**Issue by tomchr9** [kanryu/quickviewer#105]
Quickview does not show StatusBar on fullscreen startup. 

Selecting 'Show StatusBar' and 'Fullscreen on startup' options will let you see the StatusBar on fullscreen. However, restart Quickview and the StatusBar is hidden on fullscreen.

**Comment by kanryu** [comment]
The status bar is not displayed at full screen. This is the specification of QuickViewer.

**Comment by tomchr9** [comment]
Yes, but since the 'Show StatusBar' is selectable via 'View' menu - together with the 'Fullscreen on startup', it would be quite helpful if the option was remembered at the next restart, instead of having to TAB twice to get fullscreen AND the statusbar at every restart.
