### ISSUE TITLE
Don't create files in AppData (windows)

### ISSUE THREAD

**Issue by eddiezato** [kanryu/quickviewer#106]
QuickViewer v1.1.5 (x64), Windows 10.
The app creates file
`%localappdata%\QuickViewer\thumbnail.sqlite3.db`
I found same file in program folder
`QuickViewer\database\thumbnail.sqlite3.db`
How can avoid creating one in AppData?

**Comment by kanryu** [comment]
Thanks for letting me know :)

When I tried again, neither QuickViewer-1.1.4- (x86 / x64) nor 1.1.5-x64 thumbnail.sqlite3.db was copied.
I think there is a problem with the implementation of the program to copy at the first start. It will be fixed by the next release.

**Comment by kanryu** [comment]
We made a commit to fix the bug you mentioned earlier. 
You will get it on the next release.

Thanks!
