### ISSUE TITLE
Potential License Issue

### ISSUE THREAD

**Issue by kah0922** [kanryu/quickviewer#110]
ResizeHalf has no license file included in the repository. As explained by [this link](https://choosealicense.com/no-permission/), this means the software is not opensource and, if I understand this correctly, the creator could file a take down.

To avoid this from happening, either remove ResizeHalf from quickviewer, or ask the creator to license it under a GPL-3.0 compatible license.

The package maintainer for quickviewer on the AUR explains this issue [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=quickviewer).

On another note, for package maintainers it would be nice if unrar was an optional dependency, as it is not free software. Perhaps just using 7zip to open the rar files would work?

**Comment by kanryu** [comment]
@kah0922 You noticed well :)

ResizeHalf is a library that I personally requested @chikuzen to display huge images faster. Therefore, as long as it is used as a part of QuickViewer, there is no problem with licensing. I told him this problem.

> The package maintainer for quickviewer on the AUR explains this issue here.

Who is the package maintainer of AUR? I do not know.

As you know, unrar has a special license. In other words, although the source code can be used as it is for the purpose of expanding the rar archive, a commercial license agreement is required for the purpose of generating one. As QuickViewer is obviously used only for the purpose of expanding, the problem of unrar does not occur.

**Comment by kanryu** [comment]
> Perhaps just using 7zip to open the rar files would work?

Because 7zip uses unrar internally, it is not a fundamental solution. However, they seem to realize the option of rar function independently. (It may only be used for the purpose of disabling it)

**Comment by kanryu** [comment]
I made it.
