### ISSUE TITLE
[Feature Request] Show all images in a Line

### ISSUE THREAD

**Issue by Shellshock123** [kanryu/quickviewer#111]
A possibility that you can see all images in a line similar to kissmanga, mangakakalot or mangadex?

**Comment by kanryu** [comment]
I think it's probably a problem similar to #96 .

I'm not sure what other software is doing, so please post an image capture of the application you mentioned.

**Comment by Shellshock123** [comment]
Showing all the images in a line using the program sumtrapdf

![Untitled](https://user-images.githubusercontent.com/53384212/62048208-bf07bc00-b225-11e9-87b0-e94f57fdf505.png)

**Comment by kanryu** [comment]
Thank you for presenting a good example.

Currently, this proposal is unlikely to be realized. You can use the mechanism for prefetching the image as it is. However, the current implementation is a method in which the images are fixed side by side, and there is no assumption that three or more images will be arranged vertically and scrolled quickly.

I have no motivation to implement this feature, but if someone else implements it, I will answer if I ask in this issue.
