### ISSUE TITLE
Display resolution error

### ISSUE THREAD

**Issue by ted423** [kanryu/quickviewer#113]
notebook: 2560x1440
monitor: 1920x1080

only use monitor 
![image](https://user-images.githubusercontent.com/7042766/62458906-a6148300-b7b0-11e9-9814-93cde66ba804.png)

the picture 
![CPU天梯图-v20190101s](https://user-images.githubusercontent.com/7042766/62458923-b167ae80-b7b0-11e9-9e0f-f49818d09ac1.png)

**Comment by ted423** [comment]
windows photo 
![image](https://user-images.githubusercontent.com/7042766/62459012-ed9b0f00-b7b0-11e9-9209-fdc38554219d.png)

**Comment by kanryu** [comment]
First, QuickViewer may reduce it by a factor of two or four before displaying the image to make it appear faster.
This specification currently depends on the resolution of the primary display. Automatic shrinking may not be performed on your notebook.

If this is your unwanted behavior, changing "Maximum size to hold the image (pixel)" to a large value will prevent it from happening.

**Comment by ted423** [comment]
> First, QuickViewer may reduce it by a factor of two or four before displaying the image to make it appear faster.
> This specification currently depends on the resolution of the primary display. Automatic shrinking may not be performed on your notebook.
> 
> If this is your unwanted behavior, changing "Maximum size to hold the image (pixel)" to a large value will prevent it from happening.

It worked.

I think this is confuse me because the 100% is displayed on the bottom.

**Comment by kanryu** [comment]
Thank you. I think this article you provided is probably a bug in QuickViewer. It will be confirmed by the next release.

**Comment by ted423** [comment]
> Thank you.
> I think this issue you provided is probably a bug in QuickViewer.
> It will be confirmed by the next release :)

You're welcome
