### ISSUE TITLE
QuickViewer-1.1.7 is unable to read certain zip/rar archives

### ISSUE THREAD

**Issue by tomchr9** [kanryu/quickviewer#116]
QuickViewer is unable to open certain zip or rar archives. When it fails to open an archive it shows a black screen and sets the "Show Folder" option as a default option. Annoyingly, the "Show Folder" (i.e F4) option must now be manually deselected, if the option is unwanted upon the next restart.

**Comment by kanryu** [comment]
This bug is due to a change in the archive detection algorithm. It will be fixed at the next release. Specifically, whether the file name contains a dot [.] In addition to the extension.

**Comment by ted423** [comment]
Just want to say，Same here
