### ISSUE TITLE
QuickViewer-1.1.7 is unable to retain PageBar/StatusBar options in fullscreen startup

### ISSUE THREAD

**Issue by tomchr9** [kanryu/quickviewer#117]
When starting QuickViewer in fullscreen mode the activated PageBar/StatusBar options are not shown. If they are subsequently deactivated and reactivated, then they eventually show up, but are lost again upon next restart in fullscreen.

On the other hand, activated options such as Catalog/Folder view are retained in fullscreen mode upon restart.

Please make the these options retainable in fullscreen mode. It is a inconvenience deactivating and  reactivating them upon every restart.

**Comment by kanryu** [comment]
duplicated issue as #105
