### ISSUE TITLE
QuickViewer Crashes on file.

### ISSUE THREAD

**Issue by cwaynedavis1946** [kanryu/quickviewer#119]
Downloaded QuickViewer-portable-1.1.7-x64.  Works ok except for one file, attached.  It crashes every time on opening this file.  Tried with version I had before, 1.1.2.  Same crash.  
![BT-btt com a790](https://user-images.githubusercontent.com/45526946/70001041-46de3980-152a-11ea-8964-b631eac62534.jpg)
This is all I found in event log:

Application log entry: Information level ESENT information entry Event 1001, Error Reporting:
Log Name:      Application
Source:        Windows Error Reporting
Date:          12/2/2019 4:39:44 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      WHATMEWORRY
Description:
Fault bucket 2152742103993164821, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: QuickViewer.exe
P2: 1.1.7.0
P3: 5d88d364
P4: Qt5Core.dll
P5: 5.12.4.0
P6: 5d01c2fc
P7: c00000fd
P8: 000000000010f3e6
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2EC4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31D2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3202.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3200.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER324F.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_QuickViewer.exe_8273c2c5874c3d5f335373b5465b080761d25dc_74bffad1_6b134f1e-b5a6-4db1-b857-0a5f494f6419

Analysis symbol: 
Rechecking for solution: 0
Report Id: ca385b25-8d3f-44eb-9ffc-6791bbd85370
Report Status: 268435456
Hashed bucket: 1fb57ed238a480612de01389b18a2415
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-12-02T21:39:44.996129000Z" />
    <EventRecordID>15556</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WHATMEWORRY</Computer>
    <Security />
  </System>
  <EventData>
    <Data>2152742103993164821</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>QuickViewer.exe</Data>
    <Data>1.1.7.0</Data>
    <Data>5d88d364</Data>
    <Data>Qt5Core.dll</Data>
    <Data>5.12.4.0</Data>
    <Data>5d01c2fc</Data>
    <Data>c00000fd</Data>
    <Data>000000000010f3e6</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2EC4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31D2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3202.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3200.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER324F.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_QuickViewer.exe_8273c2c5874c3d5f335373b5465b080761d25dc_74bffad1_6b134f1e-b5a6-4db1-b857-0a5f494f6419</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>ca385b25-8d3f-44eb-9ffc-6791bbd85370</Data>
    <Data>268435456</Data>
    <Data>1fb57ed238a480612de01389b18a2415</Data>
    <Data>0</Data>
  </EventData>
</Event>

**Comment by cwaynedavis1946** [comment]
After submitting this, opened the problem file with paint, saved another copy as jpg.  Quickviewer opens the copy fine, it only crashes on the original file.  If you check this out it may not crash on the copy I sent you.  Not sure if this is worth pursuing, only reported it because at first I thought it was a problem with 1.1.7 which I had just downloaded.  However other programs open the problem file ok.

**Comment by kanryu** [comment]
Thank you for the report.

I will download and test your files later. This comment I'm writing now is a guess. Is the JPEG that you posted in this issue actually crashed your QuickViewer?

There are several possibilities.

-JPEG file is corrupted
-Meta information (example: EXIF) included in JPEG is broken
-JPEG image resolution is too large
-JPEG image space is incorrect (unfortunately Adobe pollutes most image formats!)

**Comment by cwaynedavis1946** [comment]
Yes, that's the jpg that caused the crash.  I'd put a low priority on this
though.

Wayne

**Comment by kanryu** [comment]
**THE IMAGE IS A GIF !**
