### ISSUE TITLE
Resizing shader resets from bilinear to nearest neighbour on zoom

### ISSUE THREAD

**Issue by d-uzlov** [kanryu/quickviewer#121]
When resizing shader is set to bilinear and I zoom the image with ctrl+mousewheel, image is always resized with nearest neighbour algorithm.
Image is properly resized with bilinear algorithm when I switch to next image and back, or when I switch resizing shader to bilinear after zooming.
All other shaders that I tested work as intended, only bilinear has the issue.

Tested on v1.1.7 Win x64.

**Comment by kanryu** [comment]
It was exactly what you said when you tried it. 
This is a bug :)
