### ISSUE TITLE
Key bindings are overridden on zoomed image

### ISSUE THREAD

**Issue by d-uzlov** [kanryu/quickviewer#124]
Disable "Scroll with mouse wheel on zooming" to reproduce.
If you zoom in image, so that its size exceeds the size of the program window, some of the key bindings are overridden.
Left, Right, Up, Down, mouse WheelUp, mouse WheelDown (and maybe some other) keys are overridden with functions to position the image on the screen.
I didn't find any way to change this behavior. So if I use WheelUp/WheelDown to go to prev/next image, then I have to either zoom out enough, turn on fitting, or set an additional hotkey.

Is there a way to keep key bindings (specifically mouse wheel ones) in a zoomed in state?

**Comment by kanryu** [comment]
QuickViewer deliberately disables customization of these inputs, because the Left, Right, Up, Down, mouse WheelUp, and Mouse WheelDown that you pointed out are necessary to scroll the magnified image you are currently viewing To This is necessary to provide an intuitive GUI.

**Comment by d-uzlov** [comment]
Welp, ok.
I just feel like arrow keys and 'mouse click + drag' for scrolling enlarged image is intuitive enough, and in some cases even just 'mouse click + drag' is enough. For me the fact, that some of the key bindings are getting disabled is counter-intuitive on its own.
But, I guess, it's just a matter of preferences.
