### ISSUE TITLE
Add option to disable delete confirmation

### ISSUE THREAD

**Issue by Keith94** [kanryu/quickviewer#13]
So pressing Delete can move image to recycle bin without prompt.

**Comment by kanryu** [comment]
I made it :)

**Comment by Keith94** [comment]
Nice, thanks!

**Comment by MaEtUgR** [comment]
@kanryu Thanks, makes this software so useful to quickly preview a huge amaount of pictures and get rid of all unwanted ones.
For anyone's information it's under **MenuBar (F9) - Folder - Confirm moving image to Recycle bin**.
