### ISSUE TITLE
gif not showing properly in quickviewer bug

### ISSUE THREAD

**Issue by wtfiwinomgs** [kanryu/quickviewer#141]
gif shows fine in browser, video player and some other software/windows but in quickviewer shows animation only half the gif, the other half stuck on first few frames?

NSFW https://i.imgur.com/bPUSIw0.gif

steps to reproduce: 
- download the gif
- open in quickviewer

**Comment by kanryu** [comment]
This forum is not a place to criticize sensitive videos.
The video is obviously mp4.
