### ISSUE TITLE
Crash when asked to view attached image

### ISSUE THREAD

**Issue by fire-eggs** [kanryu/quickviewer#143]
The attached (see ZIP) file is an invalid GIF file. QuickViewer shuts down if asked to view said image; other viewers correctly report it is an invalid file.

[2b5bc31d84703bfb9f371925f0e3e57d.zip](https://github.com/kanryu/quickviewer/files/4326540/2b5bc31d84703bfb9f371925f0e3e57d.zip)

**Comment by kanryu** [comment]
I think the GIF file is broken. Couldn't find app that can be displayed properly.
