### ISSUE TITLE
"Fit to Window" not working as expected for images smaller than window.

### ISSUE THREAD

**Issue by robotreto** [kanryu/quickviewer#145]
Thanks for your super program, I really like it a lot.

I have only this small issue : If you have a big monitor like a 4K, smaller pictures are not fitted to the window. They stay small and need to be zoomed in manually, but there is no zoom button "Zoom to window", and zoom mode is not automatically reset with next picture....

**Comment by kanryu** [comment]
Sorry for the late reply.
I don't have a 4K display, so I haven't seen any glitches in such an environment. If you find that verification is possible, I will try to fix it.

Thanks for the report :)

**Comment by robotreto** [comment]
Hi Kato-san,

no need for a 4K display to see the issue, just open a very small image, like a 640*480  : Even tough Fitting to window is enabled, it is not working as expected :


I would expect the following behaviour for small pictures :

1) if fit to window is disabled : leave picture 1:1 as it is currently the case. (like above example)

2) if fit to window is enabled : zoom picture until it's width or height matches the window.  (I know zooming will look ugly, but if you sit on a sofa 3 meters away from the monitor, it does not matter)

どうもありがとう

Reto.


====================
Tischhauser GmbH
Reto Tischhauser
Dipl Ing
Chesa dals Peschs
CH-7526 Chapella

Mob +41796114436
reto@tischhauser.com
====================

Am 24.03.2020 um 10:20 schrieb KATO Kanryu:

**Comment by sakkamade** [comment]
@robotreto, There is an option (at least now) `Don't enlarge small images on Fitting`, have you tried to disable it?

**Comment by robotreto** [comment]
Okay, that did the trick. I must have overlooked this option.

Thanks a lot!
Reto.

**Comment by sakkamade** [comment]
@kanryu, Please close it.
