### ISSUE TITLE
Feature Request/Question: Resize Window to Image

### ISSUE THREAD

**Issue by brsidell** [kanryu/quickviewer#150]
Is there an option to have the window size be stretched to the size of the image? The behavior I'm talking about is demonstrated in Irfanview. When you open an image the window size is set to whatever the size of the image is. If this option doesn't currently exist then I would like to request this as a feature. This feature is useful since it helps to reduce the amount of deadspace in the window when you open images that are different aspect ratios or resolutions. I have attached a link below to an example of what this looks like when scrolling through your files.

https://i.imgur.com/SJVaoLd.mp4

**Comment by kanryu** [comment]
Select the menu, [Image]-[Don't enlarge small images on Fitting] off.
