### ISSUE TITLE
How to specify the initial directory where the program starts?

### ISSUE THREAD

**Issue by Dmayset** [kanryu/quickviewer#180]
The directory opened every time the program starts is the *default picture* directory, how can I specify the default directory for the program to start?

**Comment by kanryu** [comment]
First of all, thank you for your interest in QuickViewer.
In conclusion, QuickViewer does not provide an input field to change the path of the initial folder in the left folder display (folder view), but it can be changed by editing quickviewer.ini.

I want you to search with the keyword HomeFolderPath and rewrite the path on the right side. For Windows, you need to write two backslashes (\) each.

https://github.com/kanryu/quickviewer/blob/master/QuickViewer/src/mainwindow.cpp#L708

If you're interested in programming, see where it's handled.

Specifically this line.

Please post a pull request if you find a program fix that solves your problem.

**Comment by Dmayset** [comment]
thanks
