### ISSUE TITLE
Remove sound from About message box

### ISSUE THREAD

**Issue by Gitoffthelawn** [kanryu/quickviewer#19]
Best to remove the sound from the About message box.

**Comment by kanryu** [comment]
I don't control anything in the message box sound.
It may be that Qt is doing something :)

**Comment by Gitoffthelawn** [comment]
Hmmm... When I looked through the code, I didn't see anything either... that's why I made an issue. :)

Could it be the type of message box?  Maybe it should really be a dialog box with a single OK button?

**Comment by kanryu** [comment]
(First of all, I do not think that I should fix this.)

I checked QtSDK, but first issued QAccessibleEvent with QMessageBox::showEvent().
```
void QMessageBox::showEvent(QShowEvent *e)
{
    QAccessibleEvent event(this, QAccessible::Alert);
    QAccessible::updateAccessibility(&event);
```
And in QWindowsAccessibility::notifyAccessibilityUpdate(), the sound file registered in the registry is played.

```
void QWindowsAccessibility::notifyAccessibilityUpdate(QAccessibleEvent *event)
{
    case QAccessible::Alert:
        soundName = event->object()->inherits("QMessageBox") ?
            messageBoxAlertSound(event->object()) : QStringLiteral("SystemAsterisk");
```

The reason on QuickViewer is this line.
```
    msgBox.setIcon(QMessageBox::Information);
```

**Comment by Hrxn** [comment]
I'm also for keeping the sound..

**Comment by Gitoffthelawn** [comment]
> `msgBox.setIcon(QMessageBox::Information);`

No big deal at all.  But I wonder if you replace `::Information` with a different option if the sound will get removed.

I took a look at over a dozen popular apps, and none make a sound for the About box.

Obviously, it's not a big deal, but if it's easy to change, probably should have it match standard practices.
