### ISSUE TITLE
Mislabelled File Opening Error

### ISSUE THREAD

**Issue by xd1986k** [kanryu/quickviewer#22]
When trying to open a mislabelled file as in a jpeg named png etc, will simply get a transparent background while other viewers seem to detect the correct format.

**Comment by kanryu** [comment]
The current QuickViewer is strongly tied to what the image extensions are and assumes that they are correct.
Also, it overrides Qt's normal loading process and realizes faster loading.
I have not yet tried to read the image file falsifying the extension with Qt, but at least that file will not be able to read at high speed.

**Comment by kanryu** [comment]
@xd1986k I made it :)

**Comment by xd1986k** [comment]
Awesome. Thank you.
