### ISSUE TITLE
Add shift+delete keyboard shortcut to bypass Recycle Bin

### ISSUE THREAD

**Issue by Gitoffthelawn** [kanryu/quickviewer#23]
Add shift+delete keyboard shortcut to bypass Recycle Bin when deleting an image.

**Comment by kanryu** [comment]
OK.

However, it will be added as a function, but it will not be added to the context menu. Make it changeable by KeyConfig and MouseConfig.

**Comment by kanryu** [comment]
@Gitoffthelawn 
I made it :)

**Comment by Gitoffthelawn** [comment]
Thanks! :)
