### ISSUE TITLE
QuickViewer 0.9.1 doesn't open TIFF files

### ISSUE THREAD

**Issue by vilmantasr** [kanryu/quickviewer#24]
QuickViewer 0.9.1 doesn't open TIFF files, if there is TIFF file in folder, program stops working.

TIFF file example:
https://drive.google.com/file/d/0Bz2Ge9UibPI4YlBlNUFpMTN3TFU/view?usp=sharing

**Comment by kanryu** [comment]
I will fix it on next release :)

**Comment by kanryu** [comment]
@vilmantasr 
I made it :)

However, since this case is currently asking other projects, please do not delete the image.
https://github.com/LibRaw/LibRaw/issues/93

**Comment by vilmantasr** [comment]
Now TIFF's opens, very good ;)
