### ISSUE TITLE
Effectiveness of drawing by OpenGL

### ISSUE THREAD

**Issue by kanryu** [kanryu/quickviewer#26]
In Qt 5.9.1, Direct2D backend (QPA plugin) is supported for Window, and it can draw with Direct2D instead of OpenGL.

So I experimented with switching on Windows GDI, OpenGL, Direct2D drawing method on QuickViewer.
Then Windows GDI is much faster than OpenGL, Direct2D is almost as good as OpenGL.

Switching the drawing to Windows GDI makes it impossible to use a reduction filter other than bilinear interpolation, but I think most users do not change this (Shader) option.

So, for Windows, I am actually trying to stop providing the OpenGL rendering, and to make only 2 ways which are bilinear with Windows GDI and bicubic with CPU.

However, because it leaves support on the source code, OpenGL is automatically enabled when building with other OS.

Comments?

**Comment by Hrxn** [comment]
Well, I for one did use another interpolation for the image reduction..

But not sure if that is really important. How much is the speed difference between GDI and OpenGL?
Something like 50%, or twice as fast, or 5x, 10x, or even more? Would be interesting to know..

If there are no other drawbacks, I think this is a good idea.

But on the other hand, this program already is really fast, at least that is what my subjective impression is, it feels really, _really_ fast 😄 

So it's not like that OpenGL would be slow, if anyone would think that now..

**Comment by kanryu** [comment]
I have a album which has 371 digital camera photos with a resolution of 4608 x 3456.

v0.9.2 took 33 seconds to display them all.(with OpenGL)
v0.9.3 is only 13 seconds to display. (with Windows GDI)

Please also test with the collection you have.

v0.9.3 does not include bicubic interpolation and Lanczos interpolation shader but it does not include because bicubic interpolation by CPU is usually superior and not too late.

Since the source code is left in the repository, you can build the OpenGL version of QuickViewer if you are interested :)
