### ISSUE TITLE
Deflate64 causes crashes

### ISSUE THREAD

**Issue by Chocolateiro** [kanryu/quickviewer#28]
When I open a Deflate64 .cbz file the program stops responding and immediately crashes.

**Comment by kanryu** [comment]
Current QuickViewer zip support is old with zlib / minizip, probably Deflate 64 will not be supported.

**Comment by kanryu** [comment]
https://github.com/madler/zlib/blob/master/FAQ

```
40. Does zlib support the new "Deflate64" format introduced by PKWare?

    No.  PKWare has apparently decided to keep that format proprietary, since
    they have not documented it as they have previous compression formats.  In
    any case, the compression improvements are so modest compared to other more
    modern approaches, that it's not worth the effort to implement.
```

**Comment by Chocolateiro** [comment]
I understand, I will use RAR5 from now on.

Thanks for the effort.

**Comment by kanryu** [comment]
@Chocolateiro

I made it :)

**Comment by Chocolateiro** [comment]
Wonderful!!
It is no longer necessary to reconvert my cbz to cbr.

Thank you for this great tool. My default image viewer from now.
