### ISSUE TITLE
Support for Qt4

### ISSUE THREAD

**Issue by kanryu** [kanryu/quickviewer#29]
QuickViewer can build for Qt 4 if we make some fixes.

We have already made most of the fixes in this release, but since qobject::connect () calling methods are incompatible, we have not just started here.

By building with Qt 4, it will be possible to operate on Windows XP.
Currently about 4% of the world's Windows seems to be XP.

Comments?

**Comment by Hrxn** [comment]
Well, if you ask me, just a waste of time.
Windows XP is officially dead, Microsoft does not support it anymore, and there is no convincing reason to use it anymore.

So, if the only benefit of Qt 4 support would be Windows XP, then just forget it, it's not worth the hassle.

**Comment by kanryu** [comment]
@Hrxn I agree too :)

What is the situation on Unix? In FreeBSD etc etc, the Qt which first comes in still remains version 4 even in 2017.

I have heard that the development of KDE 4 is not being said well. Is it OK if you distribute it with the Qt library just like Windows?

**Comment by barracuda156** [comment]
@kanryu I am interested in building with Qt4. Has there been a branch for it?

> So, if the only benefit of Qt 4 support would be Windows XP

@Hrxn This is not the case. Several macOS version do not have Qt5 (either a recent one or at all), so there are real-life use-cases beyond Windows.
