### ISSUE TITLE
Support for Linux and Mac

### ISSUE THREAD

**Issue by kanryu** [kanryu/quickviewer#3]
Basically QuickViewer is designed to be portable to OS other than Windows.

Previously, I confirmed that I can build and run on Ubuntu Linux.

I would like to provide it in the future if Linux users need it.

However, since experience of binary distribution for Linux is insufficient, how to create it is unknown at this time.

Also, as for Mac, there is no development environment at the moment so it can not be provided.

**Comment by tyzmodo** [comment]
Please continue releasing linux builds,I like quickviewer,it's fast and has awsome features,thank you.

**Comment by kanryu** [comment]
I do not regularly use Linux Desktop, so I can not support QuickViewer on Linux enough.

So ongoing releases need Linux users' cooperation.
Especially about features that are not working on Linux and that are necessary or convenient to use.

Linux currently builds on the following criteria.
- It realizes the main function of QuickViewer
- Run on Ubuntu 14.04.5 LTS amd64

And these functions do not work.
- Put the image file in the Recycle Bin
- Attach to mail
- Display of Raw image of digital camera
- Display and play animated PNG

**Comment by Hrxn** [comment]
Animated PNG does not work?
Why is that, if I may ask?

**Comment by kanryu** [comment]
Raw images and Animated PNG are supported by imageformats plugin, not QuickViewer.exe .

These source code is not included in the QuickViewer source tree, so it will not be built.

**Comment by Hrxn** [comment]
But it could be built? Or does that plugin only work on Windows? Would be new to me..

**Comment by hisaruki** [comment]
I can open directory and archive,  but file.

OK
```
$ QuickViewer-1.0.9-x64.AppImage ~/Desktop/
$ QuickViewer-1.0.9-x64.AppImage ~/Desktop/a.zip
$ QuickViewer-1.0.9-x64.AppImage ~/Desktop/a.cbz
```

NG
```
$ QuickViewer-1.0.9-x64.AppImage ~/Desktop/a.jpg
QIODevice::read (QFile, "/home/hisaruki/Desktop/"): device not open
```

It's not only a case from console arguments.
In a case I try to open from diarogue from GUI, It was the same result.

My environment.
```
4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_DESCRIPTION="Ubuntu 17.10"
```

**Comment by kanryu** [comment]
Fmm... I tested in my Linux PC, and it is correct.

    $ ./QuickViewer-1.0.9-x64.AppImage ~/Desktop/5_heart.png 
    "actionFullscreen"
    futureLoadImageFromFileVolume "5_heart.png" 0 ms, ResizedImage= false
    Database: connection ok
    $ uname -a
    Linux kanryu-VirtualBox 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hisaruki** [comment]
Detected.

+ Related or symlinked
+ The mimetype of path is image/*

A path matches above mentinons only causes.

I'll try to resolve it to wrapping path by `readlink -f`.
Thanks.

Succeed
```
$ /opt/QuickViewer-1.0.9-x64.AppImage /mnt/share/Pictures/ewGhF.jpg
$ /opt/QuickViewer-1.0.9-x64.AppImage `readlink -f /home/hisaruki/Pictures/ewGhF.jpg`
```

Fail
```
$ /opt/QuickViewer-1.0.9-x64.AppImage /home/hisaruki/Pictures/ewGhF.jpg
QIODevice::read (QFile, "/mnt/share/Pictures/res/ewGhF.jpg"): device not open

$ /opt/QuickViewer-1.0.9-x64.AppImage ./Pictures/ewGhF.jpg
QIODevice::read (QFile, "/mnt/share/Pictures/res/ewGhF.jpg"): device not open
```

**Comment by kanryu** [comment]
all right. This is a problem with AppImage.

I fixed it.
Please download rev2 :)

**Comment by hisaruki** [comment]
I got an error by the path with a space.
This is just ideas to quoting and multiple executions for AppRun.

```
#!/bin/bash

QVDIR=$HOME/.quickviewer

if [ ! -d $QVDIR ] ; then
  mkdir $QVDIR
fi
if [ ! -e $QVDIR/thumbnail.sqlite3.db ] ; then
  cp $APPDIR/var/database/thumbnail.sqlite3.db $QVDIR
fi

arr=()
for v in "$@"
do
  if [ -e "$v" ] ; then
    v=`readlink -f "$v"`
  fi
  arr=("${arr[@]}" "$v")
done

#printenv
echo PWD $PWD

for v in "${arr[@]}"
do
  $APPDIR/usr/bin/QuickViewer "$v" &
done
```

**Comment by kanryu** [comment]
@hisaruki I'm sorry for the late reply. In the script you wrote, the number of arguments passed to QuickViewer will be the same as the number of arguments passed to QuickViewer, so it will not work as expected by the user.

**Comment by kanryu** [comment]
I was fortunate enough to borrow a MacBook Pro from a friend, so I was able to release the OSX version of QuickViewer.
I do not know much about OSX, so I do not know how much backport is needed. I think that OSX which is probably supporting it is the latest version.
