### ISSUE TITLE
support for linux as AppImage

### ISSUE THREAD

**Issue by kanryu** [kanryu/quickviewer#30]
Hi,

QuickViewer is now support for linux distributions as portable AppImage.

It is ['QuickViewer-0.9.4-x86_64.AppImage'](https://github.com/kanryu/quickviewer/releases/tag/v0.9.4) on releases.
If you have linux pc, check it out :)

If you build on Linux PC you will be able to easily create AppImage.
But it is a laborious work for me so it will not be added to the release every time.

Comments?

**Comment by probonopd** [comment]
What distribution did you build this on?
Can you reduce the libstdc++.so.6 version used at build time to the one that comes with Ubuntu 14.04 (or any older distribution)?

Currently it crashes when trying to run on Ubuntu 14.04:

```
libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-7064/AppRun)
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-7064/usr/bin/../lib/libfileloader.so.1)
```

Example on how to solve this using Travis CI and GitHub:
https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/271247348#L605-L606

Please ping me here once a new release is available for download.

**Comment by kanryu** [comment]
I use kubuntu-17.04 .
I run checked also ubuntu-16.04.2 and Fedora Workstation 26, and works well.

I noticed that the -bundle-non-qt-libs parameter was missing, but adding nothing changed.
And I updated linuxdeployqt, but adding nothing changed.

What do I? :(

**Comment by probonopd** [comment]
Please build on (K)Ubuntu 14.04.

**Comment by kanryu** [comment]
If we do not notice the problem unless we build in the old environment, I think that the build tools are defective :(

**Comment by probonopd** [comment]
Nothing is defective, but Linux binaries in general can only run on target systems that are _no older_ than the system they were built on. So please compile on an older system.

You also cannot compile on Windows 10 and expect it to run on Windows XP.

**Comment by kanryu** [comment]
That is sadness :(
On Windows we can build programs that work correctly on Windows XP on Windows 10 if we do it carefully.
Because the C runtime library is tightly coupled with each compiler and does not depend on the version of the Windows OS.
So, we can distribute programs that run anywhere on Windows if you attach each C runtime library provided by VisualStudio and MingW to the program. (Of course we need to pay attention to the Windows API version)

I understood the culture of Linux developers, so let's prepare the old Linux in the future. Elderly people are the best!

**Comment by probonopd** [comment]
Or use a service like Travis CI that compiles it for you in the cloud.

**Comment by kanryu** [comment]
@probonopd I made it :)

I build on kubuntu-14.04.5, and use gcc-6 (Building QuickViewer requires gcc 6 or later.)

**Comment by probonopd** [comment]
With `QuickViewer-0.9.6-x86_64.AppImage`, still getting `QuickViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-7029/usr/bin/QuickViewer)`. Can you make sure that on your build machine `libstdc++.so.6` is no newer than what comes with Ubuntu 14.04 out of the box?

**Comment by probonopd** [comment]
Found the following on 

>  Sometimes you don't control the target machine (e.g. your library  needs to run on a locked-down enterprise system). In such a case you  will need to recompile your code using the version of GCC that  corresponds to their GLIBCXX version. In that case, you can do the following:  
> 1.  Look up the latest version of GLIBCXX supported by the target machine: strings /usr/lib/libstdc++.so.6 \| grep GLIBC ... Say the version is 3.4.19. 
> 2. Use https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html to find the corresponding GCC version. In our case, this is [4.8.3, 4.9.0).

Since AppImages are supposed to run on all still-supported LTS versions, you should target Ubuntu 14.04 at this point in time, which supports only `GLIBCXX_3.4.19`. Looking this up in the table means that you should use GCC 4.8.3 (or older, but __not__ newer) if you want the resulting executable to run on Ubuntu 14.04.

**Comment by kanryu** [comment]
Thank you very much for testing every time.

As you know, gcc needs to specify the target C runtime library when building itself.
gcc-6 available on Ubuntu 's package network seems to link with newer glibc.

As I wrote above, gcc-6 is required to build QuickViewer, and it will fail with gcc-5 or older. This is due to using C++11 and the CPU's new instructions.

There are mainly two solutions to this problem. One is to hand build gcc - 6 targeting glibc of Ubuntu 14.04. Another thing is to give up ;)

**Comment by kanryu** [comment]
@probonopd I checked on ubuntu-14.5-LTS LiveDVD and running OK.
(QuickViewer-0.9.6-x86-64.AppImage has been updated.)

To summarize this problem is that libstdc++.so provided by gcc does not exist on the Linux PC you are running.
Therefore we need to include libstdc++.so in AppImage.
This solution is problematic if libc6.so is too old, but it works with ubuntu - 14 LTS.

**Comment by probonopd** [comment]
That is an option, but in this case we will run into trouble if the host needs a newer libstdc++ than what is contained in the AppImage. Then crashes will happen. So I do not recommend to bundle this library.

**Comment by kanryu** [comment]
I agree with your opinion, but that is to say to all the shared libraries shipped with AppImage, only libstdc ++. So is not an exception.

AppImage's startup script should compare the shared library in the archive with the shared library on the host side and implement a mechanism to skip the archive side if the host side is new. I do not know if that is possible for SquashFS.

**Comment by probonopd** [comment]
Please check the solution given in https://github.com/AppIMage/AppImages/issues/173.
