### ISSUE TITLE
desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [kanryu/quickviewer#31]
Please make it pass [desktop-file-validate](http://manpages.ubuntu.com/manpages/xenial/man1/desktop-file-validate.1.html).

```
QuickViewer.desktop: error: line "[Desktop Entry] " ends with a space, but looks like a group. The validation will continue, with the trailing spaces ignored.

QuickViewer.desktop: error: value "Graphics" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character
```

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/271124677#L594-L595

Please only close this issue after a new release with a fix is available for download.

**Comment by kanryu** [comment]
Thanks!

But I still do not know what to do. I know little about AppImage and Desktop standards.

**Comment by kanryu** [comment]
I fixed.
It will be reflected in the next release :)

**Comment by kanryu** [comment]
@probonopd
I made it :)

**Comment by probonopd** [comment]
Thank you very much @kanryu :+1:
