### ISSUE TITLE
Artifacts in JPG images

### ISSUE THREAD

**Issue by Chocolateiro** [kanryu/quickviewer#34]
I see artifacts in JPG images, but when I convert that image to PNG this does not happen.
[Sample](https://fanart.tv/api/download.php?type=download&image=198982&section=2) (Note the color contours)

**Comment by kanryu** [comment]
Please write more concretely what is the problem for you.
On my PC 'Sample' seems to be displayed without problems.

When the supplied image is displayed in reduced size, the boundary lines of different colors become mixed colors, but this is the specification of the reduction interpolation algorithm.
If you choose nearest neighbor interpolation this problem will not occur, but you will not normally want to select.

**Comment by Chocolateiro** [comment]
Here are 2 images that explain my problem:
[Artifacts](https://images.imgbox.com/f8/ba/hwBW3Mlf_o.png) - [w/o Artifacts](https://images.imgbox.com/c1/fd/G5yM76gd_o.png)

I have tried the default settings and all interpolation settings, but the artifacts persist in each of them.

In other programs such as HoneyView, XnView, etc. this image is displayed correctly.

**Comment by kanryu** [comment]
I think that this problem is probably caused by libjpeg-turbo.

You can confirm that the behavior will change if you delete 'imageformats/qrawspeed0.dll' after QuickViewer exiting and launch the application again and load the image.

**Comment by kanryu** [comment]
@Chocolateiro I made it :)

I added an option to change, please open the options dialog for your purpose and turn off the check.

**Comment by Chocolateiro** [comment]
Excellent, now the images are displayed correctly while maintaining speed. 😃 

Thanks for the support.
