### ISSUE TITLE
Crash when launching image files in 7zip 

### ISSUE THREAD

**Issue by vatterspun** [kanryu/quickviewer#38]
Not sure how high priority this is but ... 

Setup: Win7x64, Quickviewer v.0.9.6

Steps:

1. Open a DOCX file with some images inside 7zip
2. Goto into the Word\Media file
3. Launch an image file

Defect: Program crash:

https://i.imgur.com/s23Mesl.png

**Comment by kanryu** [comment]
I am sorry but because I do not have Microsoft Office 2007 or Later, I can not deal with this as it is.

I want you to upload the sample DOCX or 7z file that causes problems by editing it to a form that does not cause problems even if redistributed.

As you know, the DOCX file is a modified zip file, but problems may occur when trying to display its contents with QuickViewer.

**Comment by vatterspun** [comment]
I tried to replicate this issue on 32-bit Windows with LibreOffice (which doesn't require you to buy anything to test this and has an excellent DOCX creator) but unfortunately it didn't crash.

**Comment by kanryu** [comment]
Perhaps I think the same problem as # 35.

**Comment by GitHubRulesOK** [comment]
Bug **may OR may not** be the same as #35
I can not get a crash on a valid Docx as described using version 0.9.6 or 7 within 7zip version 15.12
however under bug #35 version 0.9.6 or 7 as reported QV crashed on incorrect filename in zip file
it could thus be a malformed filename (same as #35) or 2007 has used a different zip format

to confirm  #38 is a bug I would need a rogue sample docx to test

**Comment by GitHubRulesOK** [comment]
@ vatterspun
try finding a bunch of suspect varied_filenames.docx
put them in a sub-folder
rename them all to varied_filenames.zip
use version 0.96 to view the zip files and move rapidly between the images
(its quicker than opening with 7zip) I have done this without a crash on dozens from various sources
if QV crashes try to isolate the zip file one at a time and post any suspects here

as a test here is a corrupt docx with valid internal images
rename it to .zip and QV will still show the images without crashing

[Sample - Copy.docx](https://github.com/kanryu/quickviewer/files/1319590/Sample.-.Copy.docx)
