### ISSUE TITLE
Hide scroll bars in full screen mode

### ISSUE THREAD

**Issue by Chocolateiro** [kanryu/quickviewer#40]
I replicate the request of the issue #37

Now that the image can be moved using the keys, I would like to be able to hide the scroll bars in full screen mode.

**Comment by kanryu** [comment]
@Chocolateiro I made it :)

**Comment by Chocolateiro** [comment]
The setting "hide scrollbars in full screen" applies to any scenario, not just full screen.
Is it possible to implement it only in full screen?

**Comment by kanryu** [comment]
Sorry, It will be fixed on next release.

**Comment by kanryu** [comment]
@Chocolateiro I made it :)

**Comment by Chocolateiro** [comment]
Works perfect now :D
