### ISSUE TITLE
Display the full file name in addition to the location path in the window title

### ISSUE THREAD

**Issue by Chocolateiro** [kanryu/quickviewer#41]
I replicate the request of the issue #37

Currently QuickViewer displays the full file path in the window title, but does not display the full file name.

It may not be prudent to include the absolute path of the file in the window title. Instead I think it's better to use the format "/image.jpg"

**Comment by kanryu** [comment]
If 'Show full path of the volume' menu is off, only the name of the volume (folder or archive) will be displayed.

I think this is enough.

**Comment by Chocolateiro** [comment]
The full path of the file is only visible in the window title when the "Show StatusBar" setting is enabled, regardless of the "Show full path of the volume" setting. Why?

**Comment by kanryu** [comment]
The contents of the title bar and status bar are the same as those of Hamana. It will be changed if a better representation method is found.

**Comment by kanryu** [comment]
Since we implemented the function to customize the text format, we abolish the above function.
