### ISSUE TITLE
Hide page bar permanently

### ISSUE THREAD

**Issue by Chocolateiro** [kanryu/quickviewer#42]
I replicate the request of the issue #37

It is annoying that the page bar pops up when you move the cursor under the image. Especially when you want to change instances using the Windows taskbar at the bottom, furthermore, when an image is large enough for the horizontal scroll bar to be displayed, it is superimposed over the page bar.

**Comment by kanryu** [comment]
@Chocolateiro I made it :)

**Comment by Chocolateiro** [comment]
Fantastic, I can finally hide the page bar, but the problem of the scrollbar superimposed over the page bar persists. I think this must be annoying for those who make use of it.

**Comment by kanryu** [comment]
I think there is no problem with this function.
This flag is affected only when displaying the page bar with mouse hover.

Currently the display of the scroll bar is changed regardless of the state of the full screen.
