### ISSUE TITLE
Supports touch panel input

### ISSUE THREAD

**Issue by kanryu** [kanryu/quickviewer#43]
QuickViewer supports touch panel input from the next release.

Currently it corresponds to the following input:

 - ~~Right~~ Left swipe at the bottom of the screen
    - Next Page
 - ~~Left~~ Right swipe at the bottom of the screen
    - Prev Page
 - Right swipe at the bottom of the screen with two fingers
    - Next One Page
 - Left swipe at the bottom of the screen with two fingers
    - Prev One Page
- Swipe up with two fingers
    - Fullscreen

If you have the operation method you desire and corresponding action, please comment :)

**Comment by GitHubRulesOK** [comment]
Two fingers seems to have no effect (cant get fullscreen)
On my system Lower Left to Right swipe goes previous, is that correct
•Right to Left swipe at the top of the screen Moves zoomed in document to the Left (Hand icon)
•Left to Right swipe at the top of the screen Moves zoomed in document to Right (Hand icon)
It would be nice to use pinch / spread to zoom in /out

**Comment by kanryu** [comment]
Sorry, Swipe left and right reversed.
This operation is reversed in direction by the flag of 'Bound on the right side'.

Two finger swipes may differ depending on OS and tablet models.
I tested a Lenovo tablet with Windows 10 installed.

Although pinch operation is implemented, we only implemented relatively simple operations this time.

**Comment by GitHubRulesOK** [comment]
Ok could be my tablet hardware
Small Acer 1420p (with touchscreen) Win7x64
touchpad drivers may need update
other useful option would be 2 finger rotate for picture formats that don't have EXIF rotation data

**Comment by kanryu** [comment]
There is a high possibility that the PC of Windows 8 or earlier is not compatible with multi-touch.
If they do not support multi-touch, you can not use all two finger swipe and pinch operations.

It may be better to design it so that it can be substituted by Ctrl or Shift key.

Normally, single touch touch panel will be entered by finger gesture (mouse gesture).

**Comment by GitHubRulesOK** [comment]
I can confirm touchpad (NOT touchscreen) will zoom in out
touch pad is temperamental on rotate etc. so larger movements on touchscreen are preferred

**Comment by kanryu** [comment]
If we respond to image size change and rotation by pinch operation, it would be desirable to cancel the operation by double tap.

Mouse gesture input would be preferable if it supports PCs that can not be multi-touch, but it probably conflicts with touch panel input. It will be provided in a form that can be used either way.

**Comment by kanryu** [comment]
I implemented.
