### ISSUE TITLE
Very minor visual bug

### ISSUE THREAD

**Issue by GitHubRulesOK** [kanryu/quickviewer#45]
If I rotate an image under some limited conditions the un-rotated image is kept in the background until another significant action forces a refresh
![untitled1](https://user-images.githubusercontent.com/12754913/30936834-f6fe01e6-a3cc-11e7-8545-a6309bccfc99.png)

This behaviour continues as I navigate through other images

![untitled](https://user-images.githubusercontent.com/12754913/30937128-c9552b4c-a3cd-11e7-9888-41c838964738.png)

**Comment by kanryu** [comment]
There are two possible causes for this problem.

1. When using 'Bicubic interplation by CPU' the rotation result is incorrect
1. If the image discarding at the time of switching fails for some reason, the next image is displayed with the dust image remaining.

Although [1] is a known problem, its priority is not high, so it has not been fixed yet.
The cause is unknown [2], so we do not know the cause.

**Comment by GitHubRulesOK** [comment]
Shader is set to default Bilinear (fast)
It does not happen after small images are rotated
 only once a big image such as the 2200x1700 sample or a zoomed in "fitted" 800 x 600 image is rotated ,
 so it seems to be when the rotation exceeds the visible canvas

**Comment by kanryu** [comment]
I found a problem in which an image larger than the window was displayed, rotated, and 'fitting' was canceled and enlarged, it would not be displayed properly. But this seems to be different from what you point out.

If you can check it, please write down the procedure of the operation that causes the problem.

**Comment by GitHubRulesOK** [comment]
OK after a little experimentation it may be toolbar interference
It does NOT happen if the toolbar is floating and all buttons are visible
It does NOT happen if I have only some of the toolbar visible and press R for rotate
IT DOES happen once the toolbar is extended/expanded to a temporary second line on top of the image so that I can select the rotate button then click it

**Comment by GitHubRulesOK** [comment]
It seems to be related to those toolbar actions selected on the lower line 

upper line works as expected the first image shows fit works  so that part of the image is overlayed by toolbar

If rotate is on the top line it works ok 

![1](https://user-images.githubusercontent.com/12754913/30941881-8cdc235c-a3df-11e7-8830-b859bf45766f.png)

BUT if its on the second line it fails

![2](https://user-images.githubusercontent.com/12754913/30941912-b0a2b4c2-a3df-11e7-8f79-e45159a579ae.png)

even just using fit on the second line causes issues

![3](https://user-images.githubusercontent.com/12754913/30941919-bb4b73d2-a3df-11e7-9655-eab737b99b56.png)

**Comment by kanryu** [comment]
OK. This is fixed.
Wait for next release :)

**Comment by GitHubRulesOK** [comment]
Ok looking forward to testing if I can close this one,
 again I'm impressed that you have done it within 24 hours

**Comment by kanryu** [comment]
@GitHubRulesOK I made it :)

**Comment by GitHubRulesOK** [comment]
OK very well done
I agree, in version 1.0,  I can no longer reproduce bug
Issue Closed
