### ISSUE TITLE
Key config not working in fullscreen mode

### ISSUE THREAD

**Issue by zoidbergthepopularone** [kanryu/quickviewer#47]
Hi!

Sometime between version 0.9.6 and 1.0.2, some controls stopped working when in full screen mode. For example, I have a following modified keyboard config:

actionNextPage="L, Right, Space, PgDown"
actionNextVolume=Ctrl+J
actionPrevPage="H, Left, Backspace, PgUp"
actionPrevVolume=Ctrl+K

In 0.9.6, when in fullscreen, I could use either Left or PgUp to go to the previous page and Right or PgDown to go to the next page. In 1.0.2, these keys work properly in normal view, but not in fullscreeen - then only Left and Right function, but PgUp and PgDown don't seem to be doing anything.

The same thing is true for:

actionFullscreen="F11, Return"
actionMaximizeOrNormal=Num+Enter

When in normal view, I can press Return to get to full screen, but once in fullscreen, Return is ignored.  I don't know whether this was OK in 0.9.6, though.

Zoidberg.

**Comment by kanryu** [comment]
I found that if we assign a shortcut assigned to some Action to another Action by default, that setting may be lost.

Since it has already been fixed, please wait until the next release :)

**Comment by zoidbergthepopularone** [comment]
I am afraid the fix does not actually work :-(

I am attaching an .ini file. Add it to 1.0.3 release, run QuickViewer.exe and open an image folder. The first image will display, but you can't move to the next image using PageDown - Right works, Space works, L works, but PgDown does not. If I remove all the alternates for actionNextPage and only leave PgDown, the alternates stop working (which is expected), but PgDown still fails to work (so it's not a problem of too many shortcuts).

**Comment by zoidbergthepopularone** [comment]
Hmm, attaching doesn't seem to work. I'll paste it here then.

[View]
Fitting=true
DualView=false
StayOnTop=false
RightSideBook=false
WideImageAsOnePageInDualView=true
FirstImageAsOnePageInDualView=false
ShowToolBar=false
ShowSliderBar=false
ShowStatusBar=true
ShowMenuBar=true
ShowSubfolders=false
SlideShowWait=5000
MaxTextureSize=4096
MaxVolumesCache=5
MaxImagesCache=100
BackgroundColor=ff000000
BackgroundColor2=ff5e5e5e
UseCheckeredPattern=false
DontEnlargeSmallImagesOnFitting=false
ShowFullscreenSignage=false
UseDirect2D=true
SeparatePagesWhenWideImage=false
UseFastDCTForJPEG=true
ShowPanelSeparateWindow=false
LargeToolbarIcons=false
HidePageBarParmanently=false
HideScrollBarInFullscreen=true
TitleTextFormat=%v
StatusTextFormat=%p (%n)[%s(%m)] %f %2| %p [%s(%m)] %f
TopWindowWhenRunWithAssoc=true
TopWindowWhenDropped=true
LoupeTool=false

[WindowState]
RestoreWindowState=false
WindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x2/\0\0\0\xfc\0\0\x5O\0\0\x3n\0\0\x2\x37\0\0\x1\x1a\0\0\x5G\0\0\x3\x66\0\0\0\0\0\0\0\0\a\x80)
WindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3\x11\0\0\x2\"\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0m\0\x61\0i\0n\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
BeginAsFullscreen=true

[File]
AutoLoaded=true
MaxHistoryCount=36
History=
MaxBookmarkCount=20
Bookmarks=@Invalid()
ProhibitMultipleRunning=false
LastViewPath=
DontSavingHistory=false
ExtractSolidArchiveToTemporaryDir=true

[Folder]
HomeFolderPath=
FolderSortMode=OrderByName
OpenVolumeWithProgress=true
ShowReadProgress=true

[Catalog]
CatalogViewModeSetting=Icon
MaxSearchByCharChanged=10000
MaxShowFrontpage=1000
TitleWithoutOptions=false
SearchTitleWithOptions=false
ShowTagBar=true
IconLongText=false

[KeyConfig]
actionAppVersion=
actionAutoLoaded=
actionCatalogIconLongText=
actionCatalogTitleWithoutOptions=
actionCheckVersion=
actionClearBookmarks=
actionClearHistory=
actionContextMenu=
actionCopyFile=Ctrl+Shift+C
actionCopyPage=Ctrl+C
actionDeletePage=Shift+Del
actionDontEnlargeSmallImagesOnFitting=
actionDualView="Y, F10"
actionExit=
actionExitApplicationOrFullscreen=Esc
actionFastBackward="Shift+H, Num+1"
actionFastForward="Shift+L, Num+3"
actionFirstImageAsOneView=
actionFirstPage="Ctrl+H, Home"
actionFitting="M, F12, Num+*"
actionFullscreen="F11, Return"
actionLastPage="Ctrl+L, End"
actionLoadBookmark=Q
actionMailAttachment=
actionMaximizeOrNormal=Num+Enter
actionNextOnePage=
actionNextPage="L, Right, Space, PgDown"
actionNextVolume=Ctrl+J
actionOpenExif=
actionOpenFiler=
actionOpenFolder=
actionOpenKeyConfig=
actionOpenOptionsDialog=
actionPrevOnePage=
actionPrevPage="H, Left, Backspace, PgUp"
actionPrevVolume=Ctrl+K
actionProjectWeb=
actionRecyclePage=Del
actionRenameImageFile=F2
actionRestoreWindowState=
actionRightSideBook=
actionRotate=R
actionSaveBookmark=W
actionSearchTitleWithOptions=
actionShaderBicubic=
actionShaderBilinear=
actionShaderBilinearBeforeCpuBicubic=
actionShaderCpuBicubic=
actionShaderLanczos=
actionShaderNearestNeighbor=
actionShowCatalog="Ctrl+/, F6"
actionShowFolder=F4
actionShowMenuBar=F9
actionShowPageBar=
actionShowStatusBar=
actionShowToolBar=
actionSlideShow=F7
actionStayOnTop=F8
actionWideImageAsOneView=
actionZoomIn="K, Num++"
actionZoomOut="J, Num+-"
actionLargeToolbarIcons=
actionTurnPageOnLeft=
actionTurnPageOnRight=
actionLoupeTool=
actionSeparatePagesWhenWideImage=
actionShowFullscreenSignage=
actionShowPanelSeparateWindow=

[MouseConfig]
actionAppVersion=
actionAutoLoaded=
actionCatalogIconLongText=
actionCatalogTitleWithoutOptions=
actionCheckVersion=
actionClearBookmarks=
actionClearHistory=
actionContextMenu=+::RightButton
actionCopyFile=
actionCopyPage=
actionDeletePage=
actionDontEnlargeSmallImagesOnFitting=
actionDualView=
actionExit=
actionExitApplicationOrFullscreen=
actionFastBackward=
actionFastForward=
actionFirstImageAsOneView=
actionFirstPage=
actionFitting="+::RightButton+MiddleButton, Ctrl+::MiddleButton"
actionFullscreen=+::MiddleButton
actionLastPage=
actionLoadBookmark=
actionMailAttachment=
actionMaximizeOrNormal=
actionNextOnePage=
actionNextPage="+::ForwardButton, +::WheelDown"
actionNextVolume=
actionOpenExif=
actionOpenFiler=
actionOpenFolder=
actionOpenKeyConfig=
actionOpenOptionsDialog=
actionPrevOnePage=
actionPrevPage="+::BackButton, +::WheelUp"
actionPrevVolume=
actionProjectWeb=
actionRecyclePage=
actionRenameImageFile=
actionRestoreWindowState=
actionRightSideBook=
actionRotate=
actionSaveBookmark=
actionSearchTitleWithOptions=
actionShaderBicubic=
actionShaderBilinear=
actionShaderBilinearBeforeCpuBicubic=
actionShaderCpuBicubic=
actionShaderLanczos=
actionShaderNearestNeighbor=
actionShowCatalog=
actionShowFolder=
actionShowMenuBar=
actionShowPageBar=
actionShowStatusBar=
actionShowToolBar=
actionSlideShow=
actionStayOnTop=
actionWideImageAsOneView=
actionZoomIn="+::RightButton+WheelUp, Ctrl+::WheelUp"
actionZoomOut="+::RightButton+WheelDown, Ctrl+::WheelDown"

[Shader]
Effect=CpuBicubic
BicubicShaderPath=shaders/bicubic.frag
LanczosShaderPath=shaders/lanczos.frag

[Others]
UiLanguage=English
ConfirmDeletePage=true

**Comment by GitHubRulesOK** [comment]
Agree that in version 1.0.3 this is still a bug "as reported"
here are two related lines from my ini

actionNextPage="PgDown, L, Right, Space"
actionNextVolume=Ctrl+J

I have thus re-assigned PgDown from Next Volume to Next Page

It works in windowed mode BUT NOT in fullscreen

**Comment by kanryu** [comment]
@GitHubRulesOK @zoidbergthepopularone Thank you

I modified this bug once, but since I found another bug, it seems that it came to occur again as I returned some source code. I forgot to confirm because it is a malfunction that can not be checked without restarting the application.

This time I fixed it by another method. Please check with the next release.

**Comment by GitHubRulesOK** [comment]
Thanks
I can wait, as I only use fullscreen on few occasions, and its good to know you are onto it

**Comment by GitHubRulesOK** [comment]
Version 1.04 **close**s reported bug as I see it in both x86 and x64 versions

**Comment by zoidbergthepopularone** [comment]
I can confirm that 1.0.4 works fine.
