### ISSUE TITLE
Add option to not stretch small images

### ISSUE THREAD

**Issue by Keith94** [kanryu/quickviewer#5]
Hi,
I would prefer if images that are smaller than the window size can be displayed at their original size (and centered in window) without upscaling. This way, only images bigger than the window are resized down to fit, and small images still look crisp. Would be nice to have an option for it.

**Comment by NXij** [comment]
Options are the key here, the View menu could have additional options such as:
* Center Image (This should be grayed out when Fitting is turned on)
* Fit window to image (make the window dimensions adjust based on the image dimensions and if image is bigger than the screen size, fit the window and the image to the screen size, the position the window could be in the center after moving from a big image to a small one)
* Hide UI (Hide the window frames, including the scrollbars, this would also require the integration of "Hide Menubar" to the context menu)
* View 1:1 (100%), zooms the image to its native size
* Mouse panning (pan around a image which is zoomed in or does not fit the dimensions by holding down Mouse1 and dragging)

The Key config menu could include the 1:1 option, and also let the scroll up/down be defineable as a sequence.
![concept](https://user-images.githubusercontent.com/3188124/27579730-2a220908-5b31-11e7-8611-2715cbd45c56.jpg)

**Comment by kanryu** [comment]
Hi All,

If you want it, I can consider implementing it.
But as NXij says, you have to prepare more options to specify the size of the image than you think. Probably one more main menu will be added.

Currently there are plans to create a configuration dialog to add options to save memory as some users claim.
I want to improve the display of the tool bar, menu bar, and page bar.
It will be next, but your request will be realized.

If you are a software engineer, it will be faster to add the source code and post a pull request.

**Comment by anantoghosh** [comment]
I agree with @Keith94, this is the default behavior in many image viewers
Only the images which do not fit the window are resized
Smaller images are not scaled
Smaller images are centered

Currently the options are
Zoom to fit
Show 100% (No Scaling)
which is controlled by the "fitting" button

Maybe you could split the "fitting" button to two buttons and add a single more image size option - "Fit Window" or "Auto Fit"
So user can select only one of the three at a time
Zoom to fit
Show 100% (No Scaling)
Fit Window (Auto Fit)

**Comment by kanryu** [comment]
Hi All,

I made that "show original size when images smaller than window on fitting" :)

I will close this issue if we can confirm that the original request has been achieved.
Please post the remaining topics again as another issue.

**Comment by NXij** [comment]
Can confirm that the fitting works like expected now.

**Comment by Keith94** [comment]
@kanryu Yes, that works. :)
