### ISSUE TITLE
Caption Format setting does not work if status bar is disabled

### ISSUE THREAD

**Issue by Chocolateiro** [kanryu/quickviewer#50]
When setting a custom setting for Window Title Format, it does not apply when the status bar is disabled.

**Comment by kanryu** [comment]
This is a specification.

You can set the text format of the title bar and status bar, respectively, but if you do not display the status bar, the text of the title bar will be replaced with the text of the status bar.

If you want to change the format of the title bar when you do not display the status bar, please change the format of the status bar as well as the title bar.
