### ISSUE TITLE
Feature Suggestions: Fit to width, Allow for tittlebar to be hidden, only one single instance.

### ISSUE THREAD

**Issue by dragons4life** [kanryu/quickviewer#52]
Fit to width (like "fitting" but ignores height) -
https://i.imgur.com/3vY2woS.png - fit to window "fitting"
https://i.imgur.com/xuu96r4.png - fit to width

Allow for tittle bar to be hidden -
https://i.imgur.com/UBYYJ2V.png - tittle bar showing
https://i.imgur.com/QUwhoFk.png - without tittlebar

If you need help with this maybe you can look trough mpv's code?
https://github.com/mpv-player/mpv/
or https://github.com/rossy/borderless-window

Single instance - Only allow one process to be open; Only allow one of the same program to be open

Allow for brackets " [ ] " to be removed just like " ( ) " are in the catalog

**Comment by kanryu** [comment]
> Fit to width 

The realization of this function itself is not difficult.
However, it is a bit disappointing that the convenience of the 'Fitting' toggle disappears.

> tittle bar to be hidden

Since the title bar has a special meaning to the Window System, it is not easy to keep the behavior correctly when it is removed. Especially when it is necessary to deal with other than Microsoft Windows.

We probably need to add a menu that will restore the title bar from the context menu or behave like moving the window instead of the image when dragging the screen.

> Single instance

Plesese check the Settings dialog 

> Allow for brackets

In the current specification the bracket just before the title body is treated as an author or publisher. Unlike ordinary tags, these are not omitted even in omitted title notation.

```
    // Extract book title from folder name
    // from: <<<(TAG1) [Publisher(Author)] book title (TAG2) (TAG3) ...>>>
    //   to: <<<[Publisher(Author)] book title>>>

```

**Comment by dragons4life** [comment]
Well yes, majority of these are meant to have an option to toggle on and off, there is no need to remove "fitting" (fit to window) for fit to width when both can be together in the program, can they not?

Thanks for reading my suggestions.

**Comment by eddiezato** [comment]
Can't find key binding for "fit to width" option.
Also glad to have one-key option for toggle between "fit to window" and "fit to width".
Thanks.

**Comment by kanryu** [comment]
In the current version 'Fit to width' is not included in the customization target.

In the future, this function is not an independent menu, but it will be re-implemented as a switch to another Fit mode (that is, the tool bar becomes 'Fit toggle' only).
Please wait until the next release.

**Comment by kanryu** [comment]
@eddiezato I fixed. wait for next release :)

**Comment by eddiezato** [comment]
Sorry, in description of v1.0.7 release there is a mistake. Bug info about window's position not belongs to me. :)
About fitting. "Fitting on" with "fit mode -> fit to width" don't allow to scroll image. "Fitting on/off" with "fit mode -> fit to window" always make image fit to window only. I guess the setting is broken.

**Comment by kanryu** [comment]
This is a new bug. We will need to fix it immediately.

**Comment by eddiezato** [comment]
Another issues. :)
I binded some keys for setting "fit to width" and "fit to windows". But they are not working if menu is hidden. Same in fullscreen.

**Comment by kanryu** [comment]
@eddiezato Now I tested what you said, but it seems to be working properly.

If you do not check "Do not enlarge small images on fitting", there is a possibility that it seems that it does not work as you intended.

**Comment by eddiezato** [comment]
Sorry. Yeah, it works. If using Num+/ and Num+*.
I see interesting behavior. I am setting / and * for "fit to width" and "fit to window".
If menu is showing, Num+/ and Num+* also works. If menu is hidden (F9) works only just /, but not Num+/, Num+* and *.
