### ISSUE TITLE
Open files from root location

### ISSUE THREAD

**Issue by Chocolateiro** [kanryu/quickviewer#53]
When an image is opened from the root location, the program stops responding.

With the default settings the program opens, but the image is not displayed unless you go to the next one and then go back.

**Comment by kanryu** [comment]
Please tell me more about the problem you are facing.

In the Windows version, both the folder in QuickViewer.exe and the image in 'C: \' are displayed normally.

In the Linux version, images directly under your account's home directory will be displayed correctly. (Putting an image directly under the root directory '/' is not practical on Unix)

**Comment by Chocolateiro** [comment]
I'm using Windows 10 v1703 x64. The error occurs in both physical and virtual drives.
In previous versions, like version 0.8.9 I don't have that problem.

**Comment by kanryu** [comment]
Windows 7 can not confirm the problem.

I have a Windows 10 tablet at home and test it again. Please wait for a while.

**Comment by kanryu** [comment]
@Chocolateiro I made it :)

**Comment by Chocolateiro** [comment]
Wonderful. Now it works as it should.
Thanks for the effort.
