### ISSUE TITLE
Laptop Rotation problem : "Fit To width" and "Fit to window" don't follow

### ISSUE THREAD

**Issue by sebastienbo** [kanryu/quickviewer#56]
Hi,

I noticed that when I rotate my laptop in "portrait mode" that the "Fit To width" and "Fit to window" are not re-calculated

It seems that there is no rotation trigger for windows 10 to recalculate

**Comment by kanryu** [comment]
I think that behavior is a problem of implementation of Qt :(

**Comment by GitHubRulesOK** [comment]
Just to confirm it works as normal in windows 7 tablet if desktop is rotated
seem to remember there was a "tablet mode" setting in win 10  but can't test as 10 is not loaded on this machine
