### ISSUE TITLE
may be a random qt bug?

### ISSUE THREAD

**Issue by GitHubRulesOK** [kanryu/quickviewer#57]
while testing with only "fit to window" ON with a standard jpg 4600x3500 pixels (does not happen with smaller png
 I can crash QV by simply dragging the Right side and shaking it left and right quickly several times like a dog with a stick, agreed that's not normal for a grown-up user but it is a constant fail

Windows 7x64 running 32bit or 64bit QV 1.06 
many other files in directory so may be a background file loading but if I don't shake the border the application stays stable

VARIES per crash report here are 2 (first is ntdll.dll, second is Qt5Gui.dll)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	QuickViewer.exe
  Application Version:	1.0.6.0
  Application Timestamp:	5a08216c
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.23915
  Fault Module Timestamp:	59b94a16
  Exception Code:	c0000005
  Exception Offset:	0002df76
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	2057
  Additional Information 1:	e8ad
  Additional Information 2:	e8adce1c2b9e7be834b4063ac3c53863
  Additional Information 3:	e8ad
  Additional Information 4:	e8adce1c2b9e7be834b4063ac3c53863

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	QuickViewer.exe
  Application Version:	1.0.6.0
  Application Timestamp:	5a08216c
  Fault Module Name:	Qt5Gui.dll
  Fault Module Version:	5.9.1.0
  Fault Module Timestamp:	59532e46
  Exception Code:	c0000005
  Exception Offset:	002b24a9
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by kanryu** [comment]
I do not know how to reproduce it so please write it in a bit more detail.

Is it okay to drag the title bar while dragging the title bar to the right or left side of the desktop while displaying an image of 4600x3500 pixels?

**Comment by GitHubRulesOK** [comment]
not title bar
its the middle of edge so image is quickly changing / fitting from big to small to big to smaller to bigger width
thus heavily stressing the image system

**Comment by kanryu** [comment]
The left and right edges of QuickViewer's window will move images when clicked, but are you talking about that story?

If you are talking about switching between ZoomIn / ZoomOut / Fittowindow, no burden on the PC occurs as long as Bilinear interpolation.

**Comment by GitHubRulesOK** [comment]
Yes moving the edges forces the image to resize
if that is repeated quickly and often it seems to overload the system (gui recalculating / image rescaling?)
at some point it seems to be confused, give up and crash

**Comment by kanryu** [comment]
First of all, QuickViewer shrinks to 50% if the vertical or horizontal size of the image exceeds 4000px.

If Bilinear interpolation is applied, nothing will be done any further. When the size of the canvas is changed, we recalculate how big the image should be displayed, but that's it.

When bicubic interpolation by the CPU is executed, a new size image is generated each time the size of the canvas is changed. If this operation is repeated in a 32-bit environment, memory may run short. However, there will be no problem in practical use.

**Comment by GitHubRulesOK** [comment]
Confirmed it is notjust jpg since I converted file to png
Agreed "normal" use is not likely to exhibit this problem UNLESS the image is large and the setting is "Fit to width AND user tries to change their mind about the size of working window, here I moved the edge to right then left then right
The image is only part rendered then freezes and burns
![untitled](https://user-images.githubusercontent.com/12754913/33575766-9a96fe00-d935-11e7-8db6-665c922bdc80.png)

**Comment by GitHubRulesOK** [comment]
Update for version 1.0.8
Repeatable "fit to width" crash in 1.0.7 and earlier is partially fixed, DOES not crash but does "hang" (no response) for a long time then slowly recovers and continues.

**Comment by kanryu** [comment]
If you fit the image with extremely large vertical pixels to 'fit to width' extremely large images may be generated and appear to hang.
