### ISSUE TITLE
Windows - crash on delete

### ISSUE THREAD

**Issue by realSpok** [kanryu/quickviewer#59]
This application is awesome, thanks for that. 
I have encountered an issue with it though, it seems to randomly crash while deleting images under windows.

To reproduce (this is not consistent for me):
*Open an image under quickviewer
*Delete it with the hotkey
*The application crashes without any warning or error message

After the fact, the image seems successfully moved to the recycle bin.

Setup
*Windows 7 pro
*Custom hotkey for deletion : 'X'. I did not observe the bug with Del key, but I rarely use it.
*Confirm move image to recycle bin set to 'no'

Windows log report of the crash
```
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-12-14T07:07:08.000000000Z" /> 
  <EventRecordID>3829295</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>######</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>QuickViewer.exe</Data> 
  <Data>1.0.6.0</Data> 
  <Data>5a081da8</Data> 
  <Data>Qt5Core.dll</Data> 
  <Data>5.9.1.0</Data> 
  <Data>59532cdd</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000189bd3</Data> 
  <Data>3988</Data> 
  <Data>01d374aa2168cf98</Data> 
  <Data>D:\Userfiles\######\Downloads\QuickViewer\QuickViewer-1.0.6-x64\QuickViewer.exe</Data> 
  <Data>D:\Userfiles\######\Downloads\QuickViewer\QuickViewer-1.0.6-x64\Qt5Core.dll</Data> 
  <Data>659ae4a4-e09d-11e7-bd8a-34e6d707c4c3</Data> 
  </EventData>
  </Event>
```

**Comment by kanryu** [comment]
Thank you for the report.

Normally, when deleting a file, it gets the list of images of that folder again and displays the next file deleted.
If this behavior is not done in practice, you may crash trying to access a file that does not exist.

**Comment by realSpok** [comment]
Thanks for the reply. I see it happening also when there is images (.jpg) left in the folder.

**Comment by kanryu** [comment]
@realSpok  I fixed. please wait for next release :)

**Comment by realSpok** [comment]
Seems a lot better now. I tested a bit more and did not encounter further crashes.
The application still closes if you delete the last image in a selection, but this may be normal.
