### ISSUE TITLE
64-bit vs 32-bit versions

### ISSUE THREAD

**Issue by Gitoffthelawn** [kanryu/quickviewer#6]
Thank you for writing and publishing this excellent application.

I see you are compiling both 64-bit and 32-bit versions.

Given that individual image sizes *rarely* exceed 100MB, what are the advantages/disadvantages of using the QuickViewer 64-bit vs the 32-bit version?

**Comment by kanryu** [comment]
Thank you for using this application.

Currently there is no functional difference between 32 bit version and 64 bit version.
However, performance difference is great. Reading large JPEGs and resizing by CPU is usually faster in the 64 bit version.

In addition, this application caches archives such as many images and zip in memory. You will notice that as you open many images and archives one after the other, the amount of memory usage increases.
In some cases it may exceed 2 GB.

I basically advance the use of the 64 bit version, but even with the 32 bit version it will not be a problem in normal use.

**Comment by Gitoffthelawn** [comment]
Thank you Kato. :)
