### ISSUE TITLE
Toolbar popup while using Loupe tool

### ISSUE THREAD

**Issue by xd1986k** [kanryu/quickviewer#62]
Hello
Could you disable toolbar popup when the mouse scrolls to the top while loupe tool is active?

**Comment by kanryu** [comment]
You can already set it like that.

Open the setting dialog and check "Hide tool bar in full screen". It will be the behavior you want.

In addition, Quickviewer's Loupe tool is designed to scroll the image without moving to the edge of the window.

**Comment by xd1986k** [comment]
Thank you. This is exactly what I wanted.
