### ISSUE TITLE
Startup speed

### ISSUE THREAD

**Issue by Wlkus** [kanryu/quickviewer#63]
Is there any option of setting, which can influence startup speed of program? It takes around 2-3s to start program to show image (loading to fullscreen, but windowed is same). Got 4,2 GHz quadcore, so no issues with hardware.

Any futher images load lightning fast, just program startup takes some time. Dont take me wrong, program is superb and I love it a lot, just would love it even more if it was able to start immediately :-)

**Comment by kanryu** [comment]
Please note three points about your problem.

1. use x64 edition(because QuickViewer uses extensive CPU instructions)
1. uncheck for 'Auto load last used'
1. uncheck for 'Open with Subfolders Image'

If you do not display images, application launch will not be delayed.

**Comment by Wlkus** [comment]
Checked all three, already used x64, unchecked Auto load and found Open with subfolders off by default.

But probably found out reason of slow start - I put app in Program Files foder (64bit). And that caused at least 2s delay on start. Moved it out and its working fine now - probably some kind of conflict with strict windows access rights to program folders in Windows 10 as app is running in user not admin mode.
