### ISSUE TITLE
[Feature Request] Hide vertical scrollbar in "fit to width" mode

### ISSUE THREAD

**Issue by eddiezato** [kanryu/quickviewer#64]
Will be great to have option for hide vertical scrollbar in "fit to width" mode.
And I see some annoying behavior in this mode. I recorded video for the best explanation.
https://streamable.com/2ysjj

**Comment by kanryu** [comment]
1. open setting dialog
1. check on 'Hide scroll bars in full screen'

**Comment by eddiezato** [comment]
Only affects in fullscreen, but not in windowed.

**Comment by kanryu** [comment]
Or, check on the menu 'Scroll with mouse cursor on zooming'

**Comment by eddiezato** [comment]
Wow, very good option! Thanks.
But simply hide scrollbar in window like in fullscreen will be great also. If it is not too hard for implement. :)
