### ISSUE TITLE
Consider Adding JPEG2000 Decoding Support

### ISSUE THREAD

**Issue by agungindrawan** [kanryu/quickviewer#66]
First, I want to thank you for releasing this blazing fast image viewer.

Would you consider adding JPEG2000 decoding support? :-)

**Comment by kanryu** [comment]
I will respond with the next release :)

**Comment by Hrxn** [comment]
Haven't seen JPEG2k in a long time..

Has it gained traction now, at least a bit? Some websites actually using this?

**Comment by kanryu** [comment]
I plan to support JPEG 2000, JPEG XR, HEIF. Although it may become part of it when it notices that it is hard to implement.

**Comment by kanryu** [comment]
Support for displaying HEIF is technically possible.
But it is not suitable for distribution as a QuickViewer because it is required by HEVC's software decoder :(

**Comment by Hrxn** [comment]
But using this HEVC package from Microsoft Store is possible, at least on Windows 10, or not?

**Comment by kanryu** [comment]
Yes. at least Windows 10. or ffmpeg with wrapper for HEVC.

**Comment by kanryu** [comment]
@agungindrawan I made it :)

**Comment by agungindrawan** [comment]
Thank you @kanryu :-) I tried it with some JPEG2000 file I had inside zip archives and it displayed perfectly.
