### ISSUE TITLE
Zoom in to the center of currently displayed area of the photo

### ISSUE THREAD

**Issue by onuralparslan** [kanryu/quickviewer#70]
When I click on Zoom in button, I expect to see magified view of the center of currently displayed area of the photo, but Quickviewer shows a different part of the photo. Sometimes, it shows an area that was not even in the displayed area before pressing zoom in button. Could you align it to zoom into the center of the currently displayed area?

**Comment by kanryu** [comment]
There is no function as you think, but QuickViewer has the function 'Scroll with mouse cursor on zooming'. You may be able to do something close to what you think.

Basically, QuickViewer is designed with the theme of how fast a large image can be displayed at high speed, but has some zoom function.
