### ISSUE TITLE
Sort order selecting.

### ISSUE THREAD

**Issue by hisaruki** [kanryu/quickviewer#76]
Please add the function selecting to sort order of filenames. At leaset **_numerical_** .

# Asis
* [file0, file1, file10, file2, file3, file4, file5, file6, file7, file8, file9]
# Tobe
* [file0, file1, file2, file3, file4, file5, file6, file7, file8, file9, file10]

**Comment by sakkamade** [comment]
Was this closed because this should have been corrected?
