### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by legate** [kanryu/quickviewer#77]
I am encountering compilation errors when trying to build the project in QtCreator following the instructions at https://github.com/kanryu/quickviewer/blob/master/HowToBuild.md

Environment:
Windows 10 64-bit
Qt version: Qt 5.11.0 64-bit for Desktop (MSVC 2017)
QuickViewer commit 0a4fe4e936436094350509fa0f4e97854ddda9d5

Errors:
```
..\..\quickviewer\QuickViewer\src\models\fileoperator.cpp(3): error C2511: 'FileOperator::FileOperator(QString,QObject *)': overloaded member function not found in 'FileOperator'
..\..\quickviewer\QuickViewer\src\models\fileoperator.cpp(4): error C2550: 'FileOperator::{ctor}': constructor initializer lists are only allowed on constructor definitions
```

I've uploaded the complete build logs here: https://pastebin.com/MQtaeycU

**Comment by kanryu** [comment]
Sorry, I am currently implementing new features in this project, it seems that non-complete source code has been committed.

This repository is tagged with revisions released in each version, so please build it back in the past.

**Comment by legate** [comment]
Thanks, building the latest release (v1.1.0) worked.
