### ISSUE TITLE
Instant crash of latest 1.1.0 on multiple systems

### ISSUE THREAD

**Issue by GitHubRulesOK** [kanryu/quickviewer#80]
Download and unpack latest 1.1.0-x36
Running on Win 10 PRO x64 latest install 1803 ~~can't check version as **SETTINGS > SYSTEM > ABOUT  ALSO CRASHES !!**  (may thus be related)~~ correction Win 10 currently stabilised at Version 17134.112 however it should be KB4284848 (OS Build 17134.137) 
Program opens OK (no files selected as none in user\username\pictures)
All settings left at default value, if necessary can navigate UP to see images OK,
~~however before or after clicking on home icon and QV instantly closes without warning
Once home has been selected then it behaves as expected, it only crashes when initially not set.~~

correction  QV is now crashing under several conditions, 
~~will check further on other Win 10 and close issue if it appears machine specific~~

**Comment by kanryu** [comment]
QuickViewer - 1.1.0 has known problems. That is, when you move to a subfolder with FolderView, it aborts when there is no image in the subfolder. Your problem may be the same cause as this problem. It will be fixed in the next release.

**Comment by GitHubRulesOK** [comment]
Thanks for the heads up
I suspect this install may have issues I will bear your comments in mind and look forward to next release

**Comment by GitHubRulesOK** [comment]
Confirmed with fresh download on seperate machines any significant use of left hand navigator in latest 1.1.0 x32 leads to rapid closure /crash of Qt5Core.dll  in 10 PRo x64 or 7 Pro x32

**Comment by kanryu** [comment]
You may have noticed already, but there was a change in the FolderView specification at 1.1.0.

- Initial startup
- When folders and archives are specified and there are no images inside

FolderView will be displayed automatically. There was a problem with the code added at this time, the above problem occurred.

**Comment by GitHubRulesOK** [comment]
@kanryu 
I understand time is limited when busy with other projects,
 and it can be daunting to try to close many bugs  at once.
 thanks for your diligence in resolving those that arise as soon as you can.

In this case there is still one remaining related issue #78 
however since this main bug is closed I will now close this issue
and transfer any further comments to #78
