### ISSUE TITLE
FR: Pointing device button actions

### ISSUE THREAD

**Issue by Gitoffthelawn** [kanryu/quickviewer#9]
Can you add pointing device button actions?

Examples:

1. Click (or double-click) to zoom (with zoom centered on that position).
2. Select region to zoom via pointing device selection.
3. Next/previous image.

Perhaps can be customizable via key config.

**Comment by kanryu** [comment]
Currently, the following operations are assigned to the main window with respect to the mouse input.

- Wheel Down/Forward Button:
    - NextImage
- Wheel Up/Backward Button:
    - PrevImage
- Wheel Click:
    - ToggleFullscreen

I want to realize mouse gesture and input by touch pad's swipe. However, Qt seems to be inadequate in these correspondences. (Especially on Windows)

We will implement an option dialog from now on, but I want to prepare a customize screen there. Is that okay?

**Comment by Gitoffthelawn** [comment]
That sounds good.

Most touch pads don't have a mouse wheel... they only have buttons and gestures.

**Comment by kanryu** [comment]
@Gitoffthelawn 
I made it.
I think that 'Ctrl + mouse wheel turning' is the input method for general image resizing :)

**Comment by Gitoffthelawn** [comment]
Thanks.  I'll try it out soon. :)
