### ISSUE TITLE
qtexttranslator.cpp and qtexttranslator.h don't exist.

### ISSUE THREAD

**Issue by ZanderChang** [kanryu/quickviewer#92]
It's strange that I can't find qtexttranslator.cpp and qtexttranslator.h which should be in the folder qlanguageselector and none of them exist in github. Please tell me how can I fix it.

**Comment by kanryu** [comment]
Sorry.
The submodule of QLanguageSelector referenced in QuickViewer's repository seems to be outdated. Basically this will be fixed by updating it. I am planning to do it tonight.

**Comment by kanryu** [comment]
@ZanderChang I made it :)

**Comment by ZanderChang** [comment]
@kanryu Thank you, It works!
